### ISSUE TITLE
Publish 2.0 release on crates.io

### ISSUE THREAD

**Issue by fintelia** [jansol/squish-rs#7]
This crate has accumulated a bunch of improvements since it was last published on crates.io three years ago. Would you be willing to publish a new release there so that other crates can use those? Either a `2.0` release, or even if there's other interface changes you're hoping to make before that, perhaps a `2.0-beta1`.

**Comment by jansol** [comment]
Yes, that has been in my plans for a long time. I've wanted to get in the BC1 vs BC1 with transparency separation before I do that. And if the `image` crate maintainers have some wishes regarding the API it would be nice to get them in with 2.0 too, so I won't have to make more API changes for a while.

I could do a beta release if that helps.

**Comment by fintelia** [comment]
Doing a beta would help. The image crate tries to be tolerant of breaking changes in its dependencies by not exposing them as part of the public API, so some internal usage could be ported over without waiting for the full squish-rs 2.0 release. It would also let us encourage downstream users to rely on squish-rs instead of the image's subpar DXT handling.

**Comment by jansol** [comment]
Published 2.0.0-beta1

**Comment by jansol** [comment]
Proper 2.0 release is up under the name of the expansion project, [texpresso](https://crates.io/crates/texpresso)
